# Generated by Django 4.2.21 on 2025-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Phone number')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Verification code')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Teacher login')], default=1, verbose_name='Code type')),
                ('is_used', models.PositiveSmallIntegerField(choices=[(1, 'Used'), (2, 'Unused')], default=2, verbose_name='Used or not')),
                ('updated_at', models.IntegerField(default=0, verbose_name='Updated timestamp')),
                ('created_at', models.IntegerField(default=0, verbose_name='Created timestamp')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration time')),
            ],
            options={
                'verbose_name': 'SMS Verification Code',
                'verbose_name_plural': 'SMS Verification Code Records',
                'db_table': 'sms_verifications',
            },
        ),
    ]
