# Generated by Django 4.2.21 on 2025-05-10 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=20, unique=True, verbose_name='Phone Number')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='Nickname')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Gender')),
                ('course_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Teaching Hours')),
                ('avatar_url', models.CharField(default='', max_length=255, verbose_name='Avatar URL')),
                ('background', models.TextField(blank=True, null=True, verbose_name='Personal Background')),
                ('video_url', models.CharField(default='', max_length=255, verbose_name='Introduction Video URL')),
                ('education_school', models.CharField(default='', max_length=100, verbose_name='Alma Mater')),
                ('education_level', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Bachelor'), (2, 'Master'), (3, 'PhD')], default=0, verbose_name='Education Level')),
                ('teaching_start_date', models.DateField(blank=True, null=True, verbose_name='Start Date of Teaching')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('teaching_experience', models.TextField(blank=True, null=True, verbose_name='Teaching Experience')),
                ('success_cases', models.TextField(blank=True, null=True, verbose_name='Success Cases')),
                ('teaching_achievements', models.TextField(blank=True, null=True, verbose_name='Teaching Achievements')),
                ('evaluation', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Rating')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='Is Recommended')),
                ('updated_at', models.IntegerField(default=0, verbose_name='Updated Timestamp')),
                ('created_at', models.IntegerField(default=0, verbose_name='Created Timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
            },
        ),
    ]
