# Generated by Django 4.2.21 on 2025-05-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsverification',
            options={'managed': False, 'verbose_name': 'SMS Verification Code', 'verbose_name_plural': 'SMS Verification Code Records'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False, 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
