# Generated by Django 4.2.21 on 2025-05-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_smsverification_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsverification',
            options={'verbose_name': 'SMS Verification Code', 'verbose_name_plural': 'SMS Verification Code Records'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
